name: UpdatePackage
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X GET -G 'https://script.google.com/macros/s/AKfycbxltBuZ_29oBnlxdXOIOjiZrnWY3mVAe34cZ4uUxalTS4Pm4ZGL_igseMFS-hAvH4RoXA/exec' -d 'sha=${{github.sha}}' -d 'name=es.jacksparrot.ui'
